### ISSUE TITLE
Version of pynio on conda-forge is incorrect

### ISSUE THREAD

**Issue by marylhaley** [conda-forge/pynio-feedstock#11]
One of the PyNIO developers pointed out to me that in the recipe for pynio, the version of pynio was was changed from "1.5.0-beta" to just "1.5.0". 

I'm the head of the team that develops PyNIO and related software, and we have not yet officially released 1.5.0.  We are concerned that the conda-forge version says "1.5.0", because this doesn't indicate that it is still in beta.

We greatly appreciate that somebody made the effort to put pynio under conda-forge, but we ask that this version be renamed back to "1.5.0-beta".  We would also be happy to take on the maintenance of the pynio conda-forge recipe if this helps.

**Comment by ocefpaf** [comment]
That is not true: see https://github.com/conda-forge/pynio-feedstock/blob/master/recipe/meta.yaml#L2

> We would also be happy to take on the maintenance of the pynio conda-forge recipe if this helps.

Awesome! I am mostly maintaining this due to requests from the community but I am not a user of `pynio`. It will great if you want to take over!

The process to become a maintainer is to send a PR to this `feedstock` adding your GitHub handle to the [list of maintainer](https://github.com/conda-forge/pynio-feedstock/blob/master/recipe/meta.yaml#L55-L58). Once that is merge you will get commit rights to this repository. It is also nice to keep an eye and/or become maintainer in some of the key `pynio` dependencies.

PS: I am preparing a PR to fix #10. Can I go ahead and add you as a maintainer there as well?
