### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by snowman2** [conda-forge/pynio-feedstock#23]
Why is pynio only available on Python 2?

**Comment by snowman2** [comment]
Found this:
https://github.com/NCAR/PyReshaper/issues/26

**Comment by khallock** [comment]
Hi @snowman2,

PyNIO has not yet been ported to Python 3, although we hope to offer Python 3 support later this year.

Since the lack of Python 3 support is related to PyNIO itself and not to its conda-forge recipe, I'd like to close this issue and continue any discussion on the currently open issue NCAR/pynio#10 on the PyNIO source code repository.

Thanks,
Kevin

**Comment by jhamman** [comment]
I'm reopening this issue as there will need to be changes to the PyNio recipe to enable a Python 3 build.

**Comment by ocefpaf** [comment]
Done in #38 , to install from dev label you can do:

```shell
$ conda install -c conda-forge/label/dev pynio
```
